version: "3.9"

services:
  backend:
    build: ./backend
    container_name: meapi-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///me_playground.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: meapi-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
